import type { Metadata } from "next";

import "../styles/globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Provider from "../components/Provider";

export const metadata: Metadata = {
  title: "GasWait",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>
        <Provider>
            <Header />
            <main className="app-container">{children}</main>
            <Footer />
        </Provider>
      </body>
    </html>
  );
}
